Repository Team-LionHeart/LionHeart-Server, pull requests merged in 2023-07, with the labels that each got.

#5 Feat/#4 엔티티 등록
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Article.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleCategory.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleContent.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleContentType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleImage.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Category.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/ArticleBookmark.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Attendance.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Challenge.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/ChallengeLevelType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/ChallengePopupType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Member.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Onboarding.java
Labels: ✨ feat

#3 Feat/#2 CI/CD 파이프라인 구축
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
  .github/workflows/CI-dev.yml
  .github/workflows/CI-prod.yml
  appspec.yml
  build.gradle
  gradlew
  lionheart-api/src/main/resources/application.yml
  scripts/deploy.sh
  scripts/switch.sh
Labels: 🔧 chore

#13 Refactor/#8 로그인 로직 코드 리팩토링
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/AuthInterceptor.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/resolver/MemberIdResolver.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/swagger/SwaggerConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CreateTokenService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberServiceUtils.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/LionHeartCommonRoot.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/Constraint.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/JwtKey.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/ProfileType.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/RedisKey.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/AuthErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/MemberErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/dto/ApiResponse.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/BadGatewayException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ConflictException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ForbiddenException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/InternalServerException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/LionHeartException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/NotFoundException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/UnAuthorizedException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ValidationException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/JwtUtils.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/MessageUtils.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/UuidUtils.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/MemberRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/MemberRepositoryImpl.java
  lionheart-external/src/main/java/com/chiwawa/lionheart/external/client/auth/kakao/WebClientKakaoCaller.java
Labels: ♻️ refactor

#7 Feat/#6 카카오 로그인 기능 추가
  lionheart-api/build.gradle
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/WebConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/Auth.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/AuthInterceptor.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/redis/RedisConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/resolver/MemberId.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/resolver/MemberIdResolver.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/swagger/SwaggerConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/auth/AuthController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/AuthService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/AuthServiceProvider.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CommonAuthService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CreateTokenService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/LoginRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/SignUpRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/TokenRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/response/TokenResponse.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/impl/KakaoAuthService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberServiceUtils.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/dto/request/CreateMemberRequestDto.java
  lionheart-api/src/main/resources/application-local.yml
  lionheart-api/src/main/resources/messages/validation.properties
  lionheart-common/build.gradle
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/Constraint.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/JwtKey.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/ProfileType.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/RedisKey.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/AuthErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/MemberErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/BadGatewayException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ConflictException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ForbiddenException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/InternalServerException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/LionHeartException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/NotFoundException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/UnAuthorizedException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/ValidationException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/JwtUtils.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/MessageUtils.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/UuidUtils.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Member.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/MemberRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/MemberRepositoryImpl.java
  lionheart-external/src/main/java/com/chiwawa/lionheart/external/client/auth/kakao/KakaoApiCaller.java
  lionheart-external/src/main/java/com/chiwawa/lionheart/external/client/auth/kakao/WebClientKakaoCaller.java
  lionheart-external/src/main/java/com/chiwawa/lionheart/external/client/auth/kakao/dto/response/KakaoProfileResponse.java
Labels: ✨ feat

#17 Feat/#14 프로필 조회 API 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/member/MemberRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/dto/response/ProfileResponse.java
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Member.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/NotificationStatus.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Setting.java
Labels: ✨ feat, 4️⃣ Size/S

#19 Feat/#18 커리큘럼 진척도 조회 API 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/curriculum/CurriculumRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/CurriculumRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/dto/response/CurriculumProgressResponse.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/BadGatewayException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ConflictException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ForbiddenException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/InternalServerException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/LionHeartException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/NotFoundException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/UnAuthorizedException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ValidationException.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/DateUtils.java
  lionheart-external/src/main/java/com/chiwawa/lionheart/external/client/firebase/WebClientFirebaseCaller.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/service/firebase/FirebaseCloudMessageService.java
Labels: ✨ feat, 3️⃣ Size/M

#20 Feat/#15 온보딩 로직 추가
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/LoginRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/SignUpRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/impl/KakaoAuthService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/dto/request/CreateMemberRequestDto.java
  lionheart-api/src/main/resources/messages/validation.properties
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Challenge.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/ChallengeLevelType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Member.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Onboarding.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/OnboardingRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/OnboardingRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/SettingRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/repository/SettingRepositoryCustom.java
Labels: ✨ feat, 2️⃣ Size/L

#26 Feat/#16 카테고리 별 아티클 조회 기능 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/article/ArticleRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/ArticleRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/articleContent/ArticleContentServiceUtils.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/articleTag/ArticleTagServiceUtils.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/CategoryArticleDto.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/CategoryArticleResponse.java
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/CategoryErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/model/LionHeartException.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Article.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleCategory.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Category.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleContent/ArticleContent.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleContent/ArticleContentType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleContent/repository/ArticleContentRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleContent/repository/ArticleContentRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleContent/repository/ArticleContentRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleTag/ArticleTag.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleTag/repository/ArticleTagRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleTag/repository/ArticleTagRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/articleTag/repository/ArticleTagRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryImpl.java
Labels: ✨ feat, 1️⃣ Size/XL

#29 Feat/#22 챌린지 진척도 조회 API 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/challenge/ChallengeRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/ChallengeRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/ChallengeServiceUtils.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/dto/response/ChallengeProgressResponse.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/ChallengeErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/AttendanceRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/AttendanceRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/AttendanceRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepositoryImpl.java
Labels: ✨ feat, 3️⃣ Size/M

#28 Feat/#21 북마크 생성 기능 추가
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/WebConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/swagger/SwaggerConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/ArticleBookmark/ArticleBookmarkController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articleBookmark/ArticleBookmarkService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articleBookmark/ArticleBookmarkServiceUtils.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articleBookmark/dto/request/UpdateArticleBookmarkRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/SignUpRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/dto/request/CreateMemberRequest.java
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/ArticleBookmarkErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/ArticleErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/ArticleBookmark.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Onboarding.java
Labels: ✨ feat, 3️⃣ Size/M

#37 Fix/#35 챌린지 조회 API dto 수정 #35
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/dto/response/ChallengeProgressResponse.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/dto/response/ProfileResponse.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/DateUtils.java
Labels: ⚡️ fix, 4️⃣ Size/S

#33 Feat/#27 오늘의 아티클 푸시알림 기능 구현
  lionheart-api/src/main/resources/application-local.yml
  lionheart-api/src/main/resources/sql/data.sql
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/dto/WeekAndDay.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/notification/TodayArticleNotification.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/notification/repository/TodayArticleNotificationRepository.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/notification/repository/TodayArticleNotificationRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/notification/repository/TodayArticleNotificationRepositoryImpl.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/config/scheduler/SchedulerConfig.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/config/scheduler/SchedulerErrorHandler.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/service/scheduler/SchedulerService.java
Labels: ✨ feat, 2️⃣ Size/L

#32 Feat/#31 아티클 북마크 목록 조회 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/articlebookmark/ArticleBookmarkController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/articlebookmark/ArticleBookmarkRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/ArticleBookmarkRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/dto/response/ArticleBookmarkResponse.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/dto/response/ArticleSummaryDto.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryImpl.java
Labels: ✨ feat, 3️⃣ Size/M

#40 Feat/#34 모든 회원에게 커스텀 푸시 알림 전송 API 추가
  lionheart-api/build.gradle
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/sqs/SqsConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/sqs/producer/SqsProducer.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/notification/NotificationController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/notification/dto/request/CustomNotificationRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/NotificationService.java
  lionheart-api/src/main/resources/application-dev.yml
  lionheart-api/src/main/resources/application-local.yml
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/dto/sqs/FirebaseDto.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/dto/sqs/MessageDto.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/config/sqs/consumer/SqsConsumer.java
Labels: ✨ feat, 2️⃣ Size/L

#39 Feat/#38 커리큘럼뷰 프로그레스바 로직 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/CurriculumRetrieveService.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/DateUtils.java
Labels: ✨ feat, 4️⃣ Size/S

#41 ✨: feat 주차별 아티클 조회 기능 구현 #25
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/article/ArticleRetrieveController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/ArticleRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleSummaryDto.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleSummaryResponse.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryImpl.java
Labels: ✨ feat, 3️⃣ Size/M

#44 Feat/#43 회원 탈퇴 API 추가
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/member/MemberController.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberService.java
Labels: ✨ feat, 3️⃣ Size/M

#45 Feat/#42 관리자 권한 확인용 어노테이션 구현
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/WebConfig.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/admin/Admin.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/admin/AdminCheckHandler.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/admin/AdminInterceptor.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/notification/NotificationController.java
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/AuthErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/Member.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/member/MemberRole.java
Labels: ✨ feat, 2️⃣ Size/L

#51 🐛: bugfix DTO 필드 오류 해결 #50
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleBookmarkSummaryDto.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/dto/response/ArticleBookmarkResponse.java
Labels: 🐛 bugfix

#49 Fix/#48 커리큘럼 뷰 조회 API D-Day 정보 추가
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/dto/response/CurriculumProgressResponse.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/util/DateUtils.java
Labels: ⚡️ fix, 4️⃣ Size/S

#47 ✨: feat 슬랙 Webhook으로 미처리 예외알림 기능 구현 #46
  lionheart-api/build.gradle
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/sqs/producer/SqsProducer.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/notification/dto/request/SlackNotificationRequest.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/NotificationService.java
  lionheart-api/src/main/resources/application-dev.yml
  lionheart-api/src/main/resources/application-local.yml
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/MessageType.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/dto/sqs/SlackDto.java
  lionheart-notification/build.gradle
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/config/sqs/consumer/SqsConsumer.java
  lionheart-notification/src/main/java/com/chiwawa/lionheart/notification/service/slack/SlackMessageService.java
  lionheart-notification/src/main/resources/application-dev.yml
  lionheart-notification/src/main/resources/application-local.yml
Labels: ✨ feat

#53 ⚡️: fix 아티클 조회 DTO에 아티클ID 포함 #52
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleBookmarkSummaryDto.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleSummaryDto.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/TodayArticleResponse.java
Labels: ⚡️ fix, 5️⃣ Size/XS

#55 ⚡️: fix 커리큘럼 조회 DTO 에 태명 정보 삭제 #54
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/CurriculumRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/curriculum/dto/response/CurriculumProgressResponse.java
Labels: ⚡️ fix, 5️⃣ Size/XS

#57 Fix/#56 아티클 조회방식 변경
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Article.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/ArticleType.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/repository/ArticleRepositoryImpl.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryImpl.java
Labels: ⚡️ fix, 1️⃣ Size/XL

#59 🐛: bugfix 아티클 조회시 출석 존재하지 않을때 예외처리 되는 문제 해결 #58
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/ArticleRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/ChallengeService.java
  lionheart-api/src/main/resources/application-local.yml
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/constant/message/AttendanceErrorMessage.java
  lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/article/Article.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Attendance.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepositoryCustom.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/repository/ChallengeRepositoryImpl.java
Labels: 🐞 bug, 1️⃣ Size/XL

#62 Fix/#60 출석 관련 세부 로직 추가
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/ArticleRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/challenge/ChallengeService.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Challenge.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/ChallengeLevelType.java
Labels: ⚡️ fix, 2️⃣ Size/L

#66 Fix/#65 ChallengePopupType 제거
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/ArticleRetrieveService.java
  lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/article/dto/response/ArticleSummaryResponse.java
  lionheart-api/src/main/resources/sql/schema.sql
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/Challenge.java
  lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/challenge/ChallengePopupType.java
Labels: ⚡️ fix, 3️⃣ Size/M
